### PR TITLE
Create howinternetworks.md

### PR DESCRIPTION
**Pull request by camiximena**

### CODE REVIEW

**Comment by aradhnataneja** [comment]
@camiximena - this was the very basic but vital information. often we dont even think about what happens when we turn on our computers, so this was a very simple but helpful class! Think about all those numbers that create complicated IP addresses, that we just take for granted. :computer: :dash:

**Comment by mattlistro** [comment]
@camiximena lgtm

**Comment by kdandola** [comment]
@camiximena SO great you brought this up.  I feel like its especially important to know how the internet actually works before we start discussing developers.  A lot of people take this for granted, but at the end of the day, you have to know HOW it works before you can actually use it. :100:

**Comment by erinzlomek** [comment]
@camiximena I also thought this was interesting! I hadn’t given much thought to the mechanics of how signals reach my server, how my data is stored or how changes in these systems might affect the speed at which web pages open. However, when you think about it more deeply, the speed at which web pages open can be a make-it-or-break-it factor for media businesses that rely on page views. (I currently work in the media industry and I think about this a lot.) Consumers of digital content won’t stick around for your web site to work and seemingly small hiccups in connectivity or data storage could mean a huge drop in web traffic and potentially, revenue.

**Pull request merged**
