### PR TITLE
Simplicity

### PR DESCRIPTION
**Pull request by aradhnataneja**

### CODE REVIEW

**Comment by aradhnataneja** [comment]
Please include this! Very valuable lessons :100:

**Comment by mattlistro** [comment]
@aradhnataneja I always was way too broad in creating my user stories. I think I was thinking more of epics than individual stories. I think simple short stories are key to ensure we don't overcomplicate things.

**Comment by camiximena** [comment]
@aradhnataneja, Great post! :+1: It wasn't immediately clear to me the difference between user stories and epics, but after the last class when the professor laid out the differences, I can really see the value in thinking about user stories for your product since it puts you in the shoes of the consumer. :hand:

**Comment by aradhnataneja** [comment]
Thanks all!! Appreciate it! :star: :star: :star:

**Comment by kdandola** [comment]
@aradhnataneja I'm so glad you brought this up.  Learning about epics, user stories, and themes leads to a more a succinct message. By doing so, we are able to gauge what customers are looking for and better serve their needs going forward.  This is especially important in the startup phase! :wink:

**Comment by fabriciovaladao** [comment]
I really liked the picture you added. It illustrates very well how the cards should work! LGTM :+1:

**Pull request merged**
